### ISSUE TITLE
Solidity icon is missing.

### ISSUE THREAD

**Issue by exceedxo** [CiberTurtle/Sharp-Icons#14]
Please add Solidity (.sol) icon. I recommend Ethereum icon or something beacuse i think the black Solidity language icon is ugly.

**Comment by rylydou** [comment]
Here's what I ended up with:
![image](https://github.com/rylydou/Sharp-Icons/assets/58660466/f79e09ea-17fb-4e54-83eb-94dcf1c94432)

I tested an icon that was closer to the official logo but I eventually settled on this since the the official logo doesn't look good at smaller resolutions.

**Comment by exceedxo** [comment]
looks great! waiting for it to be updated on VSCode extension!
