### ISSUE TITLE
Missing open folder icon

### ISSUE THREAD

**Issue by ncarrezdev** [CiberTurtle/Sharp-Icons#2]
Hi ! 
Thanks for this awesome pack.
When I open a folder, the icon is the same as a closed folder. Wich is quite confusing.
There was an "open folder" icon, now it is missing, can you bring it back please ? 

Thanks in advance :)

**Comment by ncarrezdev** [comment]
I believe that an "_" is missing in icon_theme.json (line 7)

Also i saw that you have done a todo icon, can you map it to a .todo extension or something like this ? 
Thanks :)

**Comment by rylydou** [comment]
Opps I forgot to change that when I did a find and replace to remove all the _'s.

An update will be out soon once its verified.
