### ISSUE TITLE
Perl icon?

### ISSUE THREAD

**Issue by GeekRuthie** [CiberTurtle/Sharp-Icons#9]
Okay, okay, I'm an oldy moldy who nerds in Perl.  But VSCode could use an icon in your set for it!  I suggest https://github.com/dnmfarrell/Perl-Icons/blob/master/Icons/Perl_Onion_Color.svg for .pm and .pl files.

**Comment by rylydou** [comment]
It ended up looking like the tor logo

The icon: ![My icon](https://user-images.githubusercontent.com/58660466/176576454-e4490c16-a30c-42bb-8419-a85130de550a.png)

![Tor logo](https://user-images.githubusercontent.com/58660466/176575628-7791de92-3e1f-4aeb-817b-84b9f51195c7.png)
